### ISSUE TITLE
4.01 playnite-web not updating without game_db_updater

### ISSUE THREAD

**Issue by 2600box** [andrew-codes/playnite-web#392]
Hello,

I perhaps I misunderstand, but I was able to update to the 4.01 linux/x64 image of playnite_web_app and at the same time, I stopped using the game_db_updater image alongside it, as that was my understanding from the changeling and the updated readme.
I believe this pull request implemented this change:
https://github.com/andrew-codes/playnite-web/pull/375

Since doing so, and updating to the 4.01 plugin and running a sync from playnite, my instance of playnite-web does not update. 

There are some errors in the logs from within docker, hopefully they shed some light?

```

playnite_web_app-1  | 2024-06-13T07:29:20.962Z playnite-web/game-db-updater/handler/persistGameEntities Persisting game entity game with id ea6f3b96-581b-4217-a4ce-4d2353cbaa82 for topic playnite/playnite/entity/game/ea6f3b96-581b-4217-a4ce-4d2353cbaa82
playnite_web_app-1  | TypeError: Cannot use 'in' operator to search for 'url' in undefined
playnite_web_app-1  |     at $4 (/opt/playnite-web-app/server.production.js:85:8409)
playnite_web_app-1  |     at GQe (/opt/playnite-web-app/server.production.js:85:10263)
playnite_web_app-1  |     at /opt/playnite-web-app/server.production.js:85:11886
playnite_web_app-1  |     at Array.map (<anonymous>)
playnite_web_app-1  |     at ri.<anonymous> (/opt/playnite-web-app/server.production.js:85:11879)
playnite_web_app-1  |     at ri.emit (node:events:519:28)
playnite_web_app-1  |     at ri._handlePublish (/opt/playnite-web-app/server.production.js:79:333643)
playnite_web_app-1  |     at ri._handlePacket (/opt/playnite-web-app/server.production.js:79:320408)
playnite_web_app-1  |     at s (/opt/playnite-web-app/server.production.js:79:318467)
playnite_web_app-1  |     at t._write (/opt/playnite-web-app/server.production.js:79:318662)
playnite_web_app-1  | 2024-06-13T07:29:20.962Z playnite-web/game-db-updater/handler/persistGameEntities Received game entity for topic playnite/playnite/entity/game/ea6f3b96-581b-4217-a4ce-4d2353cbaa82 with payload {"backgroundImage":null,"description":null,"notes":null,"genreIds":null,"enableSystemHdr":false,"hidden":false,"favorite":false,"icon":null,"coverImage":null,"installDirectory":null,"lastActivity":null,"sortingName":"Chivalry 02 - Public Testing","gameId":"ca02598c9a5c4d5491d6431ce8e8d6e7","pluginId":"00000002-dbd1-46c6-b5d0-b1ba559d10e4","includeLibraryPluginAction":true,"gameActions":null,"platformIds":["5220a732-689f-4b75-be48-72beac0fa85a"],"publisherIds":null,"developerIds":null,"releaseDate":null,"categoryIds":null,"tagIds":null,"featureIds":null,"links":null,"roms":null,"isInstalling":false,"isUninstalling":false,"isLaunching":false,"isRunning":false,"isInstalled":false,"overrideInstallState":false,"playtime":0,"added":"2024-06-13T09:29:06.4120701+02:00","modified":"2024-06-13T09:29:20.4656611+02:00","playCount":0,"installSize":null,"lastSizeScanDate":null,"seriesIds":null,"version":null,"ageRatingIds":null,"regionIds":null,"sourceId":"c8d9b8a3-4aaf-4425-9352-0f6a1a5e6b08","completionStatusId":"92590c30-b28a-484d-ab06-c3072e6d4a87","userScore":null,"criticScore":null,"communityScore":null,"preScript":null,"postScript":null,"gameStartedScript":null,"useGlobalPostScript":true,"useGlobalPreScript":true,"useGlobalGameStartedScript":true,"manual":null,"genres":null,"developers":null,"publishers":null,"tags":null,"features":null,"categories":null,"platforms":[{"specificationId":"pc_windows","icon":null,"cover":null,"background":null,"name":"PC (Windows)","id":"5220a732-689f-4b75-be48-72beac0fa85a"}],"series":null,"ageRatings":null,"regions":null,"source":{"name":"Epic","id":"c8d9b8a3-4aaf-4425-9352-0f6a1a5e6b08"},"completionStatus":{"name":"Not Played","id":"92590c30-b28a-484d-ab06-c3072e6d4a87"},"releaseYear":null,"recentActivity":"2024-06-13T09:29:06.4120701+02:00","userScoreRating":0,"communityScoreRating":0,"criticScoreRating":0,"userScoreGroup":10,"communityScoreGroup":10,"criticScoreGroup":10,"lastActivitySegment":6,"recentActivitySegment":0,"addedSegment":0,"modifiedSegment":0,"playtimeCategory":0,"installSizeGroup":0,"isCustomGame":false,"installationStatus":1,"name":"Chivalry 2 - Public Testing","id":"ea6f3b96-581b-4217-a4ce-4d2353cbaa82"}
playnite_web_app-1  | 2024-06-13T07:29:20.962Z playnite-web/game-db-updater/handler/persistGameEntities Persisting game entity game with id ea6f3b96-581b-4217-a4ce-4d2353cbaa82 for topic playnite/playnite/entity/game/ea6f3b96-581b-4217-a4ce-4d2353cbaa82
playnite_web_app-1  | TypeError: Cannot use 'in' operator to search for 'url' in undefined
playnite_web_app-1  |     at $4 (/opt/playnite-web-app/server.production.js:85:8409)
playnite_web_app-1  |     at GQe (/opt/playnite-web-app/server.production.js:85:10263)
playnite_web_app-1  |     at /opt/playnite-web-app/server.production.js:85:11886
playnite_web_app-1  |     at Array.map (<anonymous>)
playnite_web_app-1  |     at ri.<anonymous> (/opt/playnite-web-app/server.production.js:85:11879)
playnite_web_app-1  |     at ri.emit (node:events:519:28)
playnite_web_app-1  |     at ri._handlePublish (/opt/playnite-web-app/server.production.js:79:333643)
playnite_web_app-1  |     at ri._handlePacket (/opt/playnite-web-app/server.production.js:79:320408)
playnite_web_app-1  |     at s (/opt/playnite-web-app/server.production.js:79:318467)
playnite_web_app-1  |     at t._write (/opt/playnite-web-app/server.production.js:79:318662)
playnite_web_app-1  | 2024-06-13T07:29:20.965Z playnite-web/game-db-updater/handler/persistGameEntities Received game entity for topic playnite/playnite/entity/game/f56db9b8-9695-4ffd-9199-0b91abe9412d with payload {"backgroundImage":"f56db9b8-9695-4ffd-9199-0b91abe9412d\\e17f0fda-cc5f-453e-a377-b0e17f0fb1cf.jpg","description":"Chivalry 2 is a multiplayer first person slasher inspired by epic medieval movie battles. Players are thrust into the action of every iconic moment of the era - from clashing swords, to storms of flaming arrows, to sprawling castle sieges and more.","notes":null,"genreIds":["7fab7ab2-620c-4665-b144-1c944d0992ae","c49bf5f0-6c68-4442-a9ba-daf8dca5b6bb","e4e3c784-eb91-48bf-8aba-8401c755f04d","8d198997-4c4d-46c5-8fb1-12b3cf7a11ed","2f14e212-fbb8-4419-a654-a3d8c1bd2730"],"enableSystemHdr":false,"hidden":false,"favorite":false,"icon":null,"coverImage":"f56db9b8-9695-4ffd-9199-0b91abe9412d\\8325d448-43dc-4268-bf45-13e8842dea75.jpg","installDirectory":null,"lastActivity":null,"sortingName":"Chivalry 02","gameId":"Peppermint","pluginId":"00000002-dbd1-46c6-b5d0-b1ba559d10e4","includeLibraryPluginAction":true,"gameActions":null,"platformIds":["5220a732-689f-4b75-be48-72beac0fa85a"],"publisherIds":["9beaa9ac-ca15-416a-b3bd-c58396642fc6"],"developerIds":["4e5c24c1-684e-4e3e-b50e-6ae67534cff5"],"releaseDate":{"day":8,"month":6,"year":2021},"categoryIds":null,"tagIds":null,"featureIds":["cef6176b-c2ce-434e-b5aa-9cf693596578"],"links":[{"name":"Official","url":"https://www.chivalry2.com/"},{"name":"Facebook","url":"https://www.facebook.com/Chivalrythegame"},{"name":"Twitter","url":"https://twitter.com/chivalrygame"},{"name":"YouTube","url":"https://www.youtube.com/user/TornBannerStudios"},{"name":"Epic","url":"https://www.epicgames.com/store/en-US/product/chivalry-2/home"},{"name":"Discord","url":"https://discord.gg/invite/5cr2cMp"},{"name":"Steam","url":"https://store.steampowered.com/app/1824220"},{"name":"Twitch","url":"https://www.twitch.tv/directory/game/Chivalry%20II"},{"name":"Wikia","url":"https://chivalry.wiki.gg/wiki/Chivalry_2"}],"roms":null,"isInstalling":false,"isUninstalling":false,"isLaunching":false,"isRunning":false,"isInstalled":false,"overrideInstallState":false,"playtime":0,"added":"2024-06-13T09:29:06.4140704+02:00","modified":"2024-06-13T09:29:20.7262135+02:00","playCount":0,"installSize":null,"lastSizeScanDate":null,"seriesIds":["7a540856-1896-4d12-b50f-6bebbc54857b"],"version":null,"ageRatingIds":["27907cf3-ab45-44e1-b89f-10e86fdba449"],"regionIds":null,"sourceId":"c8d9b8a3-4aaf-4425-9352-0f6a1a5e6b08","completionStatusId":"92590c30-b28a-484d-ab06-c3072e6d4a87","userScore":null,"criticScore":86,"communityScore":80,"preScript":null,"postScript":null,"gameStartedScript":null,"useGlobalPostScript":true,"useGlobalPreScript":true,"useGlobalGameStartedScript":true,"manual":null,"genres":[{"name":"Fighting","id":"7fab7ab2-620c-4665-b144-1c944d0992ae"},{"name":"Hack and slash/Beat \u0027em up","id":"8d198997-4c4d-46c5-8fb1-12b3cf7a11ed"},{"name":"Indie","id":"2f14e212-fbb8-4419-a654-a3d8c1bd2730"},{"name":"Platform","id":"c49bf5f0-6c68-4442-a9ba-daf8dca5b6bb"},{"name":"Tactical","id":"e4e3c784-eb91-48bf-8aba-8401c755f04d"}],"developers":[{"name":"Torn Banner Studios","id":"4e5c24c1-684e-4e3e-b50e-6ae67534cff5"}],"publishers":[{"name":"Tripwire Interactive","id":"9beaa9ac-ca15-416a-b3bd-c58396642fc6"}],"tags":null,"features":[{"name":"Multiplayer","id":"cef6176b-c2ce-434e-b5aa-9cf693596578"}],"categories":null,"platforms":[{"specificationId":"pc_windows","icon":null,"cover":null,"background":null,"name":"PC (Windows)","id":"5220a732-689f-4b75-be48-72beac0fa85a"}],"series":[{"name":"Chivalry","id":"7a540856-1896-4d12-b50f-6bebbc54857b"}],"ageRatings":[{"name":"PEGI 18","id":"27907cf3-ab45-44e1-b89f-10e86fdba449"}],"regions":null,"source":{"name":"Epic","id":"c8d9b8a3-4aaf-4425-9352-0f6a1a5e6b08"},"completionStatus":{"name":"Not Played","id":"92590c30-b28a-484d-ab06-c3072e6d4a87"},"releaseYear":2021,"recentActivity":"2024-06-13T09:29:06.4140704+02:00","userScoreRating":0,"communityScoreRating":2,"criticScoreRating":2,"userScoreGroup":10,"communityScoreGroup":8,"criticScoreGroup":8,"lastActivitySegment":6,"recentActivitySegment":0,"addedSegment":0,"modifiedSegment":0,"playtimeCategory":0,"installSizeGroup":0,"isCustomGame":false,"installationStatus":1,"name":"Chivalry 2","id":"f56db9b8-9695-4ffd-9199-0b91abe9412d"}
playnite_web_app-1  | 2024-06-13T07:29:20.965Z playnite-web/game-db-updater/handler/persistGameEntities Persisting game entity game with id f56db9b8-9695-4ffd-9199-0b91abe9412d for topic playnite/playnite/entity/game/f56db9b8-9695-4ffd-9199-0b91abe9412d
playnite_web_app-1  | TypeError: Cannot use 'in' operator to search for 'url' in undefined
playnite_web_app-1  |     at $4 (/opt/playnite-web-app/server.production.js:85:8409)
playnite_web_app-1  |     at GQe (/opt/playnite-web-app/server.production.js:85:10263)
playnite_web_app-1  |     at /opt/playnite-web-app/server.production.js:85:11886
playnite_web_app-1  |     at Array.map (<anonymous>)
playnite_web_app-1  |     at ri.<anonymous> (/opt/playnite-web-app/server.production.js:85:11879)
playnite_web_app-1  |     at ri.emit (node:events:519:28)
playnite_web_app-1  |     at ri._handlePublish (/opt/playnite-web-app/server.production.js:79:333643)
playnite_web_app-1  |     at ri._handlePacket (/opt/playnite-web-app/server.production.js:79:320408)
playnite_web_app-1  |     at s (/opt/playnite-web-app/server.production.js:79:318467)
playnite_web_app-1  |     at t._write (/opt/playnite-web-app/server.production.js:79:318662)
playnite_web_app-1  | 2024-06-13T07:29:20.966Z playnite-web/game-db-updater/handler/persistGameEntities Received game entity for topic playnite/playnite/entity/game/f56db9b8-9695-4ffd-9199-0b91abe9412d with payload {"backgroundImage":"f56db9b8-9695-4ffd-9199-0b91abe9412d\\e17f0fda-cc5f-453e-a377-b0e17f0fb1cf.jpg","description":"Chivalry 2 is a multiplayer first person slasher inspired by epic medieval movie battles. Players are thrust into the action of every iconic moment of the era - from clashing swords, to storms of flaming arrows, to sprawling castle sieges and more.","notes":null,"genreIds":["7fab7ab2-620c-4665-b144-1c944d0992ae","c49bf5f0-6c68-4442-a9ba-daf8dca5b6bb","e4e3c784-eb91-48bf-8aba-8401c755f04d","8d198997-4c4d-46c5-8fb1-12b3cf7a11ed","2f14e212-fbb8-4419-a654-a3d8c1bd2730"],"enableSystemHdr":false,"hidden":false,"favorite":false,"icon":null,"coverImage":"f56db9b8-9695-4ffd-9199-0b91abe9412d\\8325d448-43dc-4268-bf45-13e8842dea75.jpg","installDirectory":null,"lastActivity":null,"sortingName":"Chivalry 02","gameId":"Peppermint","pluginId":"00000002-dbd1-46c6-b5d0-b1ba559d10e4","includeLibraryPluginAction":true,"gameActions":null,"platformIds":["5220a732-689f-4b75-be48-72beac0fa85a"],"publisherIds":["9beaa9ac-ca15-416a-b3bd-c58396642fc6"],"developerIds":["4e5c24c1-684e-4e3e-b50e-6ae67534cff5"],"releaseDate":{"day":8,"month":6,"year":2021},"categoryIds":null,"tagIds":null,"featureIds":["cef6176b-c2ce-434e-b5aa-9cf693596578"],"links":[{"name":"Official","url":"https://www.chivalry2.com/"},{"name":"Facebook","url":"https://www.facebook.com/Chivalrythegame"},{"name":"Twitter","url":"https://twitter.com/chivalrygame"},{"name":"YouTube","url":"https://www.youtube.com/user/TornBannerStudios"},{"name":"Epic","url":"https://www.epicgames.com/store/en-US/product/chivalry-2/home"},{"name":"Discord","url":"https://discord.gg/invite/5cr2cMp"},{"name":"Steam","url":"https://store.steampowered.com/app/1824220"},{"name":"Twitch","url":"https://www.twitch.tv/directory/game/Chivalry%20II"},{"name":"Wikia","url":"https://chivalry.wiki.gg/wiki/Chivalry_2"}],"roms":null,"isInstalling":false,"isUninstalling":false,"isLaunching":false,"isRunning":false,"isInstalled":false,"overrideInstallState":false,"playtime":0,"added":"2024-06-13T09:29:06.4140704+02:00","modified":"2024-06-13T09:29:20.7262135+02:00","playCount":0,"installSize":null,"lastSizeScanDate":null,"seriesIds":["7a540856-1896-4d12-b50f-6bebbc54857b"],"version":null,"ageRatingIds":["27907cf3-ab45-44e1-b89f-10e86fdba449"],"regionIds":null,"sourceId":"c8d9b8a3-4aaf-4425-9352-0f6a1a5e6b08","completionStatusId":"92590c30-b28a-484d-ab06-c3072e6d4a87","userScore":null,"criticScore":86,"communityScore":80,"preScript":null,"postScript":null,"gameStartedScript":null,"useGlobalPostScript":true,"useGlobalPreScript":true,"useGlobalGameStartedScript":true,"manual":null,"genres":[{"name":"Fighting","id":"7fab7ab2-620c-4665-b144-1c944d0992ae"},{"name":"Hack and slash/Beat \u0027em up","id":"8d198997-4c4d-46c5-8fb1-12b3cf7a11ed"},{"name":"Indie","id":"2f14e212-fbb8-4419-a654-a3d8c1bd2730"},{"name":"Platform","id":"c49bf5f0-6c68-4442-a9ba-daf8dca5b6bb"},{"name":"Tactical","id":"e4e3c784-eb91-48bf-8aba-8401c755f04d"}],"developers":[{"name":"Torn Banner Studios","id":"4e5c24c1-684e-4e3e-b50e-6ae67534cff5"}],"publishers":[{"name":"Tripwire Interactive","id":"9beaa9ac-ca15-416a-b3bd-c58396642fc6"}],"tags":null,"features":[{"name":"Multiplayer","id":"cef6176b-c2ce-434e-b5aa-9cf693596578"}],"categories":null,"platforms":[{"specificationId":"pc_windows","icon":null,"cover":null,"background":null,"name":"PC (Windows)","id":"5220a732-689f-4b75-be48-72beac0fa85a"}],"series":[{"name":"Chivalry","id":"7a540856-1896-4d12-b50f-6bebbc54857b"}],"ageRatings":[{"name":"PEGI 18","id":"27907cf3-ab45-44e1-b89f-10e86fdba449"}],"regions":null,"source":{"name":"Epic","id":"c8d9b8a3-4aaf-4425-9352-0f6a1a5e6b08"},"completionStatus":{"name":"Not Played","id":"92590c30-b28a-484d-ab06-c3072e6d4a87"},"releaseYear":2021,"recentActivity":"2024-06-13T09:29:06.4140704+02:00","userScoreRating":0,"communityScoreRating":2,"criticScoreRating":2,"userScoreGroup":10,"communityScoreGroup":8,"criticScoreGroup":8,"lastActivitySegment":6,"recentActivitySegment":0,"addedSegment":0,"modifiedSegment":0,"playtimeCategory":0,"installSizeGroup":0,"isCustomGame":false,"installationStatus":1,"name":"Chivalry 2","id":"f56db9b8-9695-4ffd-9199-0b91abe9412d"}
playnite_web_app-1  | 2024-06-13T07:29:20.966Z playnite-web/game-db-updater/handler/persistGameEntities Persisting game entity game with id f56db9b8-9695-4ffd-9199-0b91abe9412d for topic playnite/playnite/entity/game/f56db9b8-9695-4ffd-9199-0b91abe9412d
playnite_web_app-1  | TypeError: Cannot use 'in' operator to search for 'url' in undefined
playnite_web_app-1  |     at $4 (/opt/playnite-web-app/server.production.js:85:8409)
playnite_web_app-1  |     at GQe (/opt/playnite-web-app/server.production.js:85:10263)
playnite_web_app-1  |     at /opt/playnite-web-app/server.production.js:85:11886
playnite_web_app-1  |     at Array.map (<anonymous>)
playnite_web_app-1  |     at ri.<anonymous> (/opt/playnite-web-app/server.production.js:85:11879)
playnite_web_app-1  |     at ri.emit (node:events:519:28)
playnite_web_app-1  |     at ri._handlePublish (/opt/playnite-web-app/server.production.js:79:333643)
playnite_web_app-1  |     at ri._handlePacket (/opt/playnite-web-app/server.production.js:79:320408)
playnite_web_app-1  |     at s (/opt/playnite-web-app/server.production.js:79:318467)
playnite_web_app-1  |     at t._write (/opt/playnite-web-app/server.production.js:79:318662)
playnite_web_app-1  | 2024-06-13T07:29:20.966Z playnite-web/game-db-updater/handler/persistAssets Received game entity asset for topic playnite/playnite/entity/game/f56db9b8-9695-4ffd-9199-0b91abe9412d/asset/8325d448-43dc-4268-bf45-13e8842dea75.jpg/type/cover
playnite_web_app-1  | 2024-06-13T07:29:20.966Z playnite-web/game-db-updater/handler/persistAssets Persisting game entity asset, cover, game with id f56db9b8-9695-4ffd-9199-0b91abe9412d and with asset ID 8325d448-43dc-4268-bf45-13e8842dea75.jpg
playnite_web_app-1  | TypeError: Cannot use 'in' operator to search for 'url' in undefined
playnite_web_app-1  |     at $4 (/opt/playnite-web-app/server.production.js:85:8409)
playnite_web_app-1  |     at VQe (/opt/playnite-web-app/server.production.js:85:9635)
playnite_web_app-1  |     at /opt/playnite-web-app/server.production.js:85:11886
playnite_web_app-1  |     at Array.map (<anonymous>)
playnite_web_app-1  |     at ri.<anonymous> (/opt/playnite-web-app/server.production.js:85:11879)
playnite_web_app-1  |     at ri.emit (node:events:519:28)
playnite_web_app-1  |     at ri._handlePublish (/opt/playnite-web-app/server.production.js:79:333643)
playnite_web_app-1  |     at ri._handlePacket (/opt/playnite-web-app/server.production.js:79:320408)
playnite_web_app-1  |     at s (/opt/playnite-web-app/server.production.js:79:318467)
playnite_web_app-1  |     at t._write (/opt/playnite-web-app/server.production.js:79:318662)
playnite_web_app-1  | 2024-06-13T07:29:20.966Z playnite-web/game-db-updater/handler/persistAssets Received game entity asset for topic playnite/playnite/entity/game/f56db9b8-9695-4ffd-9199-0b91abe9412d/asset/e17f0fda-cc5f-453e-a377-b0e17f0fb1cf.jpg/type/background
playnite_web_app-1  | 2024-06-13T07:29:20.966Z playnite-web/game-db-updater/handler/persistAssets Persisting game entity asset, background, game with id f56db9b8-9695-4ffd-9199-0b91abe9412d and with asset ID e17f0fda-cc5f-453e-a377-b0e17f0fb1cf.jpg
playnite_web_app-1  | TypeError: Cannot use 'in' operator to search for 'url' in undefined
playnite_web_app-1  |     at $4 (/opt/playnite-web-app/server.production.js:85:8409)
playnite_web_app-1  |     at VQe (/opt/playnite-web-app/server.production.js:85:9635)
playnite_web_app-1  |     at /opt/playnite-web-app/server.production.js:85:11886
playnite_web_app-1  |     at Array.map (<anonymous>)
playnite_web_app-1  |     at ri.<anonymous> (/opt/playnite-web-app/server.production.js:85:11879)
playnite_web_app-1  |     at ri.emit (node:events:519:28)
playnite_web_app-1  |     at ri._handlePublish (/opt/playnite-web-app/server.production.js:79:333643)
playnite_web_app-1  |     at ri._handlePacket (/opt/playnite-web-app/server.production.js:79:320408)
playnite_web_app-1  |     at s (/opt/playnite-web-app/server.production.js:79:318467)
playnite_web_app-1  |     at t._write (/opt/playnite-web-app/server.production.js:79:318662)
playnite_web_app-1  | 2024-06-13T07:29:20.967Z playnite-web/game-db-updater/handler/persistAssets Received game entity asset for topic playnite/playnite/entity/game/f56db9b8-9695-4ffd-9199-0b91abe9412d/asset/8325d448-43dc-4268-bf45-13e8842dea75.jpg/type/cover
playnite_web_app-1  | 2024-06-13T07:29:20.967Z playnite-web/game-db-updater/handler/persistAssets Persisting game entity asset, cover, game with id f56db9b8-9695-4ffd-9199-0b91abe9412d and with asset ID 8325d448-43dc-4268-bf45-13e8842dea75.jpg
playnite_web_app-1  | 2024-06-13T07:29:20.967Z playnite-web/game-db-updater/handler/persistAssets Received game entity asset for topic playnite/playnite/entity/game/f56db9b8-9695-4ffd-9199-0b91abe9412d/asset/e17f0fda-cc5f-453e-a377-b0e17f0fb1cf.jpg/type/background
playnite_web_app-1  | 2024-06-13T07:29:20.967Z playnite-web/game-db-updater/handler/persistAssets Persisting game entity asset, background, game with id f56db9b8-9695-4ffd-9199-0b91abe9412d and with asset ID e17f0fda-cc5f-453e-a377-b0e17f0fb1cf.jpg
playnite_web_app-1  | TypeError: Cannot use 'in' operator to search for 'url' in undefined
playnite_web_app-1  |     at $4 (/opt/playnite-web-app/server.production.js:85:8409)
playnite_web_app-1  |     at VQe (/opt/playnite-web-app/server.production.js:85:9635)
playnite_web_app-1  |     at /opt/playnite-web-app/server.production.js:85:11886
playnite_web_app-1  |     at Array.map (<anonymous>)
playnite_web_app-1  |     at ri.<anonymous> (/opt/playnite-web-app/server.production.js:85:11879)
playnite_web_app-1  |     at ri.emit (node:events:519:28)
playnite_web_app-1  |     at ri._handlePublish (/opt/playnite-web-app/server.production.js:79:333643)
playnite_web_app-1  |     at ri._handlePacket (/opt/playnite-web-app/server.production.js:79:320408)
playnite_web_app-1  |     at s (/opt/playnite-web-app/server.production.js:79:318467)
playnite_web_app-1  |     at t._write (/opt/playnite-web-app/server.production.js:79:318662)
playnite_web_app-1  | TypeError: Cannot use 'in' operator to search for 'url' in undefined
playnite_web_app-1  |     at $4 (/opt/playnite-web-app/server.production.js:85:8409)
playnite_web_app-1  |     at VQe (/opt/playnite-web-app/server.production.js:85:9635)
playnite_web_app-1  |     at /opt/playnite-web-app/server.production.js:85:11886
playnite_web_app-1  |     at Array.map (<anonymous>)
playnite_web_app-1  |     at ri.<anonymous> (/opt/playnite-web-app/server.production.js:85:11879)
playnite_web_app-1  |     at ri.emit (node:events:519:28)
playnite_web_app-1  |     at ri._handlePublish (/opt/playnite-web-app/server.production.js:79:333643)
playnite_web_app-1  |     at ri._handlePacket (/opt/playnite-web-app/server.production.js:79:320408)
playnite_web_app-1  |     at s (/opt/playnite-web-app/server.production.js:79:318467)
playnite_web_app-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

**Comment by andrew-codes** [comment]
Let me take a look.

**Comment by andrew-codes** [comment]
I think the new release of 4.0.2 will address this issue. Thanks!
