### ISSUE TITLE
ERR TypeError: The loader.load() function must be called with a value, but got: undefined.

### ISSUE THREAD

**Issue by andrew-codes** [andrew-codes/playnite-web#495]
Error when viewing My Library:

```shell
ERR TypeError: The loader.load() function must be called with a value, but got: undefined.
}
ERR TypeError: The loader.load() function must be called with a value, but got: undefined.
    at r.load (/opt/playnite-web-app/server.production.js:420:171554)
    at CV.getByRelation (/opt/playnite-web-app/server.production.js:910:32559)
    at Object.cover (/opt/playnite-web-app/server.production.js:910:42696)
    at FL1 (/opt/playnite-web-app/server.production.js:366:33989)
    at mHu (/opt/playnite-web-app/server.production.js:366:33636)
    at DL1 (/opt/playnite-web-app/server.production.js:366:38567)
    at pHu (/opt/playnite-web-app/server.production.js:366:38390)
    at q6 (/opt/playnite-web-app/server.production.js:366:34981)
    at q6 (/opt/playnite-web-app/server.production.js:366:34637)
    at UL1 (/opt/playnite-web-app/server.production.js:366:36435) {
  path: [ 'games', 247, 'cover' ],
  locations: [ { line: 4, column: 5 } ],
  extensions: [Object: null prototype] {}
}
```

**Comment by andrew-codes** [comment]
Non-issue. Caused by running multiple instances of Playnite-Web against the same database instance.
