### ISSUE TITLE
ERR BSONError: Invalid UTF-8 string in BSON document

### ISSUE THREAD

**Issue by andrew-codes** [andrew-codes/playnite-web#522]
Seeing an error after syncing when trying to load the game library.

```sh
ERR BSONError: Invalid UTF-8 string in BSON document
    at parseUtf8 (/opt/playnite-web-app/node_modules/bson/lib/bson.cjs:148:19)
    at Object.toUTF8 (/opt/playnite-web-app/node_modules/bson/lib/bson.cjs:273:21)
    at deserializeObject (/opt/playnite-web-app/node_modules/bson/lib/bson.cjs:2952:31)
    at internalDeserialize (/opt/playnite-web-app/node_modules/bson/lib/bson.cjs:2863:12)
    at Object.deserialize (/opt/playnite-web-app/node_modules/bson/lib/bson.cjs:4335:12)
    at OnDemandDocument.toObject (/opt/playnite-web-app/node_modules/mongodb/lib/cmap/wire_protocol/on_demand/document.js:208:28)
    at CursorResponse.shift (/opt/playnite-web-app/node_modules/mongodb/lib/cmap/wire_protocol/responses.js:207:35)
    at FindCursor.next (/opt/playnite-web-app/node_modules/mongodb/lib/cursor/abstract_cursor.js:222:41)
    at [Symbol.asyncIterator] (/opt/playnite-web-app/node_modules/mongodb/lib/cursor/abstract_cursor.js:159:45)
    at AsyncGenerator.next (<anonymous>) {
  path: [ 'games' ],
  locations: [ { line: 2, column: 3 } ],
  extensions: [Object: null prototype] {}
}
```

**Comment by andrew-codes** [comment]
Tracking with #532
