### ISSUE TITLE
Playnite Web Extension bug

### ISSUE THREAD

**Issue by cvele** [andrew-codes/playnite-web#564]
On occasion this will pop up during playnite startup. It's likely tied to the library update and a wild race condition or something. In any case we should be more defensive and test for missing entity.

```
01-10 11:48:38.886|ERROR|PlayniteApplication:Unhandled exception occured.
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at PlayniteWeb.PlayniteWeb.<>c__DisplayClass43_0.<HandleGameUpdated>b__4(Game g) in D:\a\playnite-web\playnite-web\apps\PlayniteWebPlugin\src\PlayniteWeb.cs:line 306
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at PlayniteWeb.PlayniteWeb.HandleGameUpdated(Object sender, ItemUpdatedEventArgs`1 e) in D:\a\playnite-web\playnite-web\apps\PlayniteWebPlugin\src\PlayniteWeb.cs:line 307
   at PlayniteWeb.PlayniteWeb.<OnApplicationStarted>b__36_0(ItemUpdatedEventArgs`1 e) in D:\a\playnite-web\playnite-web\apps\PlayniteWebPlugin\src\PlayniteWeb.cs:line 252
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value)
   at System.Reactive.ObserverBase`1.OnNext(T value)
   at System.Reactive.Subjects.Subject`1.OnNext(T value)
   at PlayniteWeb.PlayniteWeb.<.ctor>b__26_2(EventPattern`1 e) in D:\a\playnite-web\playnite-web\apps\PlayniteWebPlugin\src\PlayniteWeb.cs:line 75
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Subjects.Subject`1.OnNext(T value)
   at System.Reactive.Linq.ObservableImpl.FromEventPattern.Impl`2.<>c__DisplayClass3_0.<GetHandler>b__0(Object sender, TEventArgs eventArgs)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Playnite.Database.ItemCollection`1.OnItemUpdated(IEnumerable`1 updates) in C:\projects\playnite\source\Playnite\Database\Collections\ItemCollection.cs:line 623
   at Playnite.Database.ItemCollection`1.EndBufferUpdate() in C:\projects\playnite\source\Playnite\Database\Collections\ItemCollection.cs:line 665
   at Playnite.Database.ItemCollection`1.EventBufferHandler`1.Dispose() in C:\projects\playnite\source\Playnite\Database\Collections\ItemCollection.cs:line 35
   at Playnite.ViewModels.MainViewModelBase.UpdateGamesInstallSizes(CancellationToken token, IEnumerable`1 games, String progressMessageLocKey) in C:\projects\playnite\source\Playnite\ViewModels\MainViewModelBase.cs:line 643
   at Playnite.ViewModels.MainViewModelBase.<>c__DisplayClass129_0.<UpdateLibrary>b__0(CancellationToken token) in C:\projects\playnite\source\Playnite\ViewModels\MainViewModelBase.cs:line 598
   at Playnite.ViewModels.MainViewModelBase.<>c__DisplayClass135_0.<UpdateLibraryData>b__0() in C:\projects\playnite\source\Playnite\ViewModels\MainViewModelBase.cs:line 805
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Playnite.ViewModels.MainViewModelBase.<UpdateLibraryData>d__135.MoveNext() in C:\projects\playnite\source\Playnite\ViewModels\MainViewModelBase.cs:line 867
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Playnite.ViewModels.MainViewModelBase.<UpdateLibrary>d__129.MoveNext() in C:\projects\playnite\source\Playnite\ViewModels\MainViewModelBase.cs:line 563
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Playnite.ViewModels.MainViewModelBase.<ProcessStartupLibUpdate>d__128.MoveNext() in C:\projects\playnite\source\Playnite\ViewModels\MainViewModelBase.cs:line 553
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Playnite.FullscreenApp.FullscreenApplication.<OpenMainViewAsync>d__35.MoveNext() in C:\projects\playnite\source\Playnite.FullscreenApp\FullscreenApplication.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Playnite.FullscreenApp.ProgramEntry.Main(String[] args) in C:\projects\playnite\source\Playnite.FullscreenApp\ProgramEntry.cs:line 71

```

**Comment by cvele** [comment]
PR #565
